import asyncio
import os
import cognee

customer_data = [
    "Customer Kwame (ID: 1004) was an active user for a year, but usage dropped by 80% in the last month. He downgraded his plan and has not responded to two check-in emails from the support team.",
    "Customer Ngozi (ID: 1005) recently complained twice about slow customer support response times and mentioned she was 'considering switching to a competitor.' Her last login was 10 days ago.",
]


async def main():
    cognee.config.set_llm_provider(os.environ["LLM_PROVIDER"])
    cognee.config.set_llm_model(os.environ["LLM_MODEL"])
    cognee.config.set_llm_api_key(os.environ["LLM_API_KEY"])
    cognee.config.set_embedding_provider(os.environ["EMBEDDING_PROVIDER"])
    cognee.config.set_embedding_model(os.environ["EMBEDDING_MODEL"])
    cognee.config.set_embedding_api_key(os.environ["EMBEDDING_API_KEY"])
    cognee.config.set_embedding_dimensions(int(os.environ["EMBEDDING_DIMENSIONS"]))

    await cognee.prune.prune_data()
    await cognee.prune.prune_system(metadata=True)

    for record in customer_data:
        await cognee.add(record)

    await cognee.cognify()

    query = "Which customers show signs of churn risk, and why? List each customer by name with their risk reason."
    results = await cognee.search(query_text=query)

    print("\n" + "=" * 50)
    print("   CUSTOMER RETENTION RISK REPORT")
    print("=" * 50 + "\n")

    for result in results:
        if isinstance(result, dict) and "search_result" in result:
            for item in result["search_result"]:
                print(f"WARNING: {item}\n")
        else:
            print(result)

    print("=" * 50)
    print("Report generated by Retention Risk Agent (powered by Cognee)")
    print("=" * 50)


if __name__ == "__main__":
    asyncio.run(main())

